SESSION_TTL: "20"
API_SECRET_LENGTH: "128"
DEFAULT_LIMIT: "1000"

# REDIS:
REDIS_HOST: "localhost"
REDIS_PORT: "6379"
REDIS_CHANNEL_PREFIX: "erotrip-api"

ASSET_HOST: "http://localhost:3000"

NOTIFICATIONS_THRESHOLD: "20"

# insert this ONLY if mails should be redirected!
DELIVER_MAILS_TO: 'noreply@enginearch.com'

WEB_CLIENT_PREFIX: "http://"
WEB_CLIENT_HOST: 'localhost'
WEB_CLIENT_PORT: '9001'

CABLE_URL: 'ws://localhost:28080'