default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: erotrip_api_development
  user: lukas
  password:

test:
  <<: *default
  database: erotrip_api_test

staging:
  <<: *default
  database: erotrip_production
  username: erotrip
  password: YRMWf8PFdPF2Ughd

production:
  <<: *default
  database: erotrip_production
  username: erotrip
  password: <%= ENV['EROTRIP_API_DATABASE_PASSWORD'] %>